package com.hereliesaz.ideaz.buildlogic

import com.hereliesaz.ideaz.IBuildCallback

/**
 * Result object returned by a [BuildStep].
 * @property success True if the step completed successfully, false otherwise.
 * @property output The console output (logs/errors) generated by the step.
 */
data class BuildResult(val success: Boolean, val output: String)

/**
 * Functional interface representing a single atomic unit of work in the build pipeline.
 * Examples: Compiling Kotlin code, linking resources, signing an APK.
 */
interface BuildStep {
    /**
     * Executes the logic for this build step.
     * @param callback Optional callback for real-time logging.
     * @return [BuildResult] indicating success/failure and output logs.
     */
    fun execute(callback: IBuildCallback? = null): BuildResult
}
