package com.hereliesaz.ideaz.buildlogic

import com.hereliesaz.ideaz.IBuildCallback

/**
 * Result object returned by a [BuildStep].
 *
 * @property success True if the step completed successfully, false otherwise.
 * @property output The console output (logs/errors) generated by the step.
 * @property durationMs Wall-clock time the step took. Set by the orchestrator
 *   so individual steps don't need to track it themselves. Pre-orchestrator
 *   callers may leave this as 0.
 */
data class BuildResult(
    val success: Boolean,
    val output: String,
    val durationMs: Long = 0L,
)

/**
 * Functional interface representing a single atomic unit of work in the build
 * pipeline. Examples: compiling Kotlin code, linking resources, signing an APK.
 *
 * Steps are *blocking*. The pipeline is run inside a coroutine on
 * [kotlinx.coroutines.Dispatchers.IO]; steps should not internally launch
 * coroutines or suspend. If a step is doing meaningful work for more than a
 * second or two it should periodically check [Thread.currentThread().isInterrupted]
 * and bail out cleanly so cancellation of the surrounding coroutine has effect.
 */
interface BuildStep {
    /**
     * Short human-readable name used in progress logs. Defaults to the
     * concrete class's simple name; override only when that name is too
     * cryptic (e.g., a generic step that handles multiple cases).
     */
    val displayName: String
        get() = this::class.java.simpleName

    /**
     * Executes the logic for this build step.
     * @param callback Optional callback for real-time logging.
     * @return [BuildResult] indicating success/failure and output logs.
     *   The [BuildResult.durationMs] field will be filled in by the
     *   [BuildOrchestrator] if the step is run through one.
     */
    fun execute(callback: IBuildCallback? = null): BuildResult
}
